name       : python-musicbrainzngs
version    : 0.6
release    : 1
source     :
    - https://github.com/alastair/python-musicbrainzngs/archive/v0.6.tar.gz : ec447bcab906fe7c4dbd714a1dff1b00adcd20d0011968df1a740e6b1fb09cb5
license    :
    - BSD-2-Clause
    - ISC
component  : programming.python
summary    : Python bindings for Musicbrainz NGS webservice
description: |
    This library implements webservice bindings for the Musicbrainz NGS site, also known as /ws/2 and the Cover Art Archive.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
